name: agora_vai
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  result_dart: ^2.1.0
  result_command: ^1.3.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  provider: ^6.1.5
  go_router: ^15.1.2
  flutter_local_notifications: ^19.2.1
  flutter_timezone: ^4.1.1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
